Creating an example to filter users based on taxnomny
creativecommons/wp-plugin-creativecommons-website pull request #16
Opened 2021-10-31 13:00 UTC by shailee-m

Creating an example to filter users based on taxnomny

## Fixes
Creating an example to filter users based on taxnomny
Fixes #72 by @shailee-m 

## Description
- Creating an example to filter users based on taxnomny
- Added css files.
- Given a code structure as per my understanding. Open to suggesstions.

## Technical details
It is based on a custom taxonomy created by me. The user can filter a list of users based on a dropdown option in the UI

## Screenshots

![Untitled_ Oct 31, 2021 6_18 PM (1)](https://user-images.githubusercontent.com/10625985/139584630-192b7ed6-5d24-4c26-9de3-5bcbee7560a2.gif)

## Checklist
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the *default* branch of the repository (`main` or `master`).
- [X] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-10-31 13:06 UTC, shailee-m commented
@brylie Creating a draft request as I am still trying to figure out proper styling as per the design mock-ups. But this contains the basics of the plugin. 

For the taxonomy list, I have created a custom taxonomy myself as it was required for testing. Please provide me with taxonomy details so that I can replace them with the terms we want to use.

For displaying the taxonomy list, I have used react's entity records method as it seemed easier to integrate with the block keeping in mind the dynamic rendering of employee list based on user-selected taxonomy.

Please have a look at the code and let me know if the structure needs any changes.

2021-11-01 08:04 UTC, brylie requested changes
Add the `.DS_Store` file to `.gitignore` since it contains only [OSX metadata](https://en.wikipedia.org/wiki/.DS_Store).

2021-11-01 08:32 UTC, brylie requested changes
A few changes and an open question about template rendering. Also, use `npm` 8 to generate `package-lock.json`

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/edit.js
> +		return select( 'core' ).getEntityRecords( 'taxonomy', 'staff_position' );
The taxonomy name is `group`

https://github.com/creativecommons/wp-plugin-creativecommons-website/blob/00a6a5323c7439cbab9ba445a9c27d1741728d66/cc-author/cc-author-group-taxonomy.php#L9-L11

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/edit.js
> +	/* Display all taxonomies */
Semantically, taxonomies consist of terms. It seems that this code is listing terms of the desired taxonomy rather than listing taxonomies. If my understanding is correct, please update this comment and the following code to reflect its purpose better.

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/edit.js
> +	/* Display all taxonomies */
Even better might be to use "user group", since the select list is displaying user groups.

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/query.php
> +function get_users_list($users_to_include)
Should this argument be `$groups_to_include` since we are filtering by user group?

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/query.php
> +    $users = get_objects_in_term(array((int)$users_to_include), 'staff_position');
It seems`'staff_position'` should be `'group'`

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/edit.js
> +		return select( 'core' ).getEntityRecords( 'taxonomy', 'staff_position' );
What does `select( 'core' )` do here? It seems like `staff_position` is the taxonomy name, correct?

```suggestion
		return select( 'core' ).getEntityRecords( 'taxonomy', 'group' );
```

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/query.php
> +    if (!empty($users_to_include) && empty($users)) {
This should also be `$groups_to_include` in order to distinguish between the concepts of "`groups` taxonomy" and "WordPress users".

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/query.php
> +    if (!empty($users_to_include) && empty($users)) {
```suggestion
    if (!empty($groups_to_include) && empty($users)) {
```

2021-11-01 08:32 UTC, brylie commented on blocks/users-list/query.php
> +        $output .= '</div>';
Out of curiosity, is there a cleaner way to render an HTML template with context data in WordPress/PHP?

For example, Django has the [`render` shortcut function](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#render) that takes `request`, `template`, and `context` arguments and returns a rendered template. So, is there a similar method in WordPress/PHP that takes a `template` string and `context` and returns a template generated with the data?

The pseudo-code would look like:

```php
$user_grid_item_template = load_template( 'user_grid_item' );

foreach ($users as $user) {
    $output .= render_template_with_data( $user_grid_item_template, $user);
}
```

Even better would be to move the `foreach` into the template, using syntax similar to Jinja, Blade, or Django templates.

This template rendering approach is just an idea but would seem to improve the readability of our code and is common practice with other web development frameworks.

2021-11-01 08:32 UTC, brylie commented on package.json
> +	"dependencies": {
Make sure to use `npm` version 8 when generating `package-lock.json` so that we don't have so many line changes.

2021-11-01 08:32 UTC, brylie commented on styles/grid.css
> +	padding: 5px;
Use relative units such as `em` or `rem` for layout.

2021-11-01 08:32 UTC, brylie commented on styles/grid.css
> +	padding: 10px;
To adhere to responsive design, use `em` or `rem` values for layout.

2021-11-01 08:32 UTC, brylie commented on wp-plugin-creativecommons-website.php
> +}
I see your intent to use the `group` taxonomy, which recently merged. So let's update this pull request to use the `group` taxonomy for further testing.

2021-11-01 15:52 UTC, shailee-m commented on blocks/users-list/query.php
> +        $output .= '</div>';
I will check and update you

2021-11-01 16:04 UTC, brylie commented on blocks/users-list/query.php
> +        $output .= '</div>';
Sure. It's just an idea. The code looks great otherwise.

2021-11-01 18:14 UTC, shailee-m commented on blocks/users-list/query.php
> +        $output .= '</div>';
I think twig is a good template engine. I will integrate it and push

2021-11-03 19:20 UTC, shailee-m commented on blocks/users-list/query.php
> +function get_users_list($users_to_include)
done

2021-11-04 08:58 UTC, brylie commented on blocks/users-list/edit.js
> +				return <option key={ i } value={ taxo.id }>{ taxo.name }</option>;
Should the `key` also be `taxo.id`?
```suggestion
				return <option key={ taxo.id } value={ taxo.id }>{ taxo.name }</option>;
```

2021-11-04 10:30 UTC, brylie commented
@shailee-m does this pull request need any updates in the developer documentation to describe how the blocks plugin is structured, how to use the Composer image, etc?

2021-11-04 10:50 UTC, shailee-m commented
> @shailee-m does this pull request need any updates in the developer documentation to describe how the blocks plugin is structured, how to use the Composer image, etc?

@brylie No, I don't think it does. All basic setup instructions are there I have only added plugin content

2021-11-04 11:05 UTC, shailee-m commented
> @shailee-m does this pull request need any updates in the developer documentation to describe how the blocks plugin is structured, how to use the Composer image, etc?

regarding the composer it would install by itself

2021-11-09 15:39 UTC, shailee-m commented
@brylie This is how it finally looks.

![staff](https://user-images.githubusercontent.com/10625985/140954094-8f5b6523-3724-4d53-bb51-4d60a0716216.png)

![Untitled_ Nov 9, 2021 9_00 PM](https://user-images.githubusercontent.com/10625985/140955203-ee767234-c679-430e-93e1-ab5b11e30f2e.gif)

2021-11-10 09:37 UTC, brylie approved these changes

2021-11-10 09:37 UTC, merged

2021-11-10 09:38 UTC, brylie commented
@all-contributors please add @shailee-m for code